id: 2953a23cc1144f1dbebf08b0bb3433e8
initial_creation_type: ocr
source_metadata:
  volumes:
    4901543114214a8b86daf6674d4560a2:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ཀླུ་གཏོར་གྱི་ཆོ་ག།
      total_pages: 1349
      volume_number: 41
